### ISSUE TITLE
Bump major version in the next release

### ISSUE THREAD

**Issue by ViralBShah** [JuliaMath/SpecialFunctions.jl#360]
With https://github.com/JuliaMath/SpecialFunctions.jl/pull/297 merged, this is a reminder to bump the major version whenever we tag a new release, since we have a breaking change.

**Comment by devmotion** [comment]
If we don't want to make a new release right away, maybe we could follow ColPrac's suggestion and bump the version number to `2.0.0-DEV`? I assume this would make it less likely that accidentally it's forgotten to bump the major version.

Or, maybe one could even view https://github.com/JuliaMath/SpecialFunctions.jl/pull/297 as a bugfix that removed some type piracy (and seemed to affect only a single package)?

**Comment by ararslan** [comment]
FWIW I've never found the `-DEV` suffix to be a particularly useful convention; IMO it mostly adds overhead and commit noise.

Also, I don't think there's anything stopping us from just tagging a breaking release right now.

**Comment by ViralBShah** [comment]
Definitely should not treat it as a bugfix, because it will break code that depends on it. If there are a few other things we want to do for 2.0, we should wait for a few days. If nothing else is on the horizon, then we can just tag. There's no shortage of major version numbers, after all :-)

**Comment by ararslan** [comment]
I can't speak to what people have desired to put into the next breaking release version, though it's worth noting that this breaking change has been the only commit to master since the last release. That seems like a decent opportunity to make a new release, since it means there aren't lingering bugfixes on master that people are waiting for, so a new release wouldn't _require_ them to upgrade their supported major version in order to get some particular fix. Plus we can always go back and make more releases prior to this breaking change if needed by backporting commits.

**Comment by KristofferC** [comment]
I just want to say this here as well that this was not a good idea at all (https://github.com/JuliaMath/SpecialFunctions.jl/pull/361#issuecomment-976345119). A tiny type-piracy fix is nothing of value compared to the extreme amount of work this causes downstream.

> There's no shortage of major version numbers, after all :-)

That is not a good attitude to have when maintaining a basic library like this one. It's like saying we could just push out a Julia 2.0 tomorrow if we wanted with some small keyword change. On this repo, it is changing one number from a 1 to a 2. For the ecosystem there are countless of CompatHelper PRs, countless of new registrations etc.
